version: '3'

services:
  app:  
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
